### ISSUE TITLE
CLog is not included

### ISSUE THREAD

**Issue by ndahlquist** [liaohuqiu/android-Ultra-Pull-To-Refresh#12]
CLog is not being packaged with the AAR, and is not listed as a dependency. This forces users of this library to include Clog separately, if log output is needed (not sure if this is intentional).

```
E/AndroidRuntime(12522): FATAL EXCEPTION: main
E/AndroidRuntime(12522): Process: com.snapchat.android.flavortest, PID: 12522
E/AndroidRuntime(12522): java.lang.NoClassDefFoundError: Failed resolution of: Lin/srain/cube/util/CLog;
E/AndroidRuntime(12522): 	at in.srain.cube.views.ptr.PtrFrameLayout.onMeasure(PtrFrameLayout.java:166)
E/AndroidRuntime(12522): 	at android.view.View.measure(View.java:16537)
E/AndroidRuntime(12522): 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
E/AndroidRuntime(12522): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
E/AndroidRuntime(12522): 	at android.view.View.measure(View.java:16537)
E/AndroidRuntime(12522): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5135)
E/AndroidRuntime(12522): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime(12522): 	at android.view.View.measure(View.java:16537)
E/AndroidRuntime(12522): 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1456)
E/AndroidRuntime(12522): 	at android.view.View.measure(View.java:16537)
E/AndroidRuntime(12522): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5135)
E/AndroidRuntime(12522): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime(12522): 	at android.view.View.measure(View.java:16537)
E/AndroidRuntime(12522): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5135)
E/AndroidRuntime(12522): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime(12522): 	at android.view.View.measure(View.java:16537)
E/AndroidRuntime(12522): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5135)
E/AndroidRuntime(12522): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime(12522): 	at android.view.View.measure(View.java:16537)
E/AndroidRuntime(12522): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5135)
E/AndroidRuntime(12522): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
E/AndroidRuntime(12522): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
E/AndroidRuntime(12522): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
E/AndroidRuntime(12522): 	at android.view.View.measure(View.java:16537)
E/AndroidRuntime(12522): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5135)
E/AndroidRuntime(12522): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime(12522): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
E/AndroidRuntime(12522): 	at android.view.View.measure(View.java:16537)
E/AndroidRuntime(12522): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1947)
E/AndroidRuntime(12522): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1137)
E/AndroidRuntime(12522): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1326)
E/AndroidRuntime(12522): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1024)
E/AndroidRuntime(12522): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5796)
E/AndroidRuntime(12522): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
E/AndroidRuntime(12522): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
E/AndroidRuntime(12522): 	at android.view.Choreographer.doFrame(Choreographer.java:544)
E/AndroidRuntime(12522): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
E/AndroidRuntime(12522): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(12522): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(12522): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(12522): 	at android.app.ActivityThread.main(ActivityThread.java:5102)
E/AndroidRuntime(12522): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12522): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(12522): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(12522): Caused by: java.lang.ClassNotFoundException: Didn't find class "in.srain.cube.util.CLog" on path: DexPathList[[zip file "/data/app/com.snapchat.android.flavortest-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.snapchat.android.flavortest-1, /vendor/lib, /system/lib]]
E/AndroidRuntime(12522): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(12522): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(12522): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(12522): 	... 44 more
E/AndroidRuntime(12522): 	Suppressed: java.lang.ClassNotFoundException: in.srain.cube.util.CLog
E/AndroidRuntime(12522): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(12522): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(12522): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(12522): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(12522): 		... 45 more
E/AndroidRuntime(12522): 	Caused by: java.lang.NoClassDefFoundError: Class "Lin/srain/cube/util/CLog;" not found
E/AndroidRuntime(12522): 		... 49 more
```

**Comment by liaohuqiu** [comment]
Now, `CLog` has been added into to dependency list: https://repo1.maven.org/maven2/in/srain/cube/ultra-ptr/1.0.5/ultra-ptr-1.0.5.pom
