### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by slowfall** [liaohuqiu/android-Ultra-Pull-To-Refresh#121]
使用android-Ultra-Pull-to-Refresh，下拉刷新listview，出现以下错误：
java.lang.NullPointerException
	at in.srain.cube.views.ptr.PtrFrameLayout.sendCancelEvent(PtrFrameLayout.java:895)
	at in.srain.cube.views.ptr.PtrFrameLayout.updatePos(PtrFrameLayout.java:373)
	at in.srain.cube.views.ptr.PtrFrameLayout.movePos(PtrFrameLayout.java:360)
	at in.srain.cube.views.ptr.PtrFrameLayout.access$400(PtrFrameLayout.java:17)
	at in.srain.cube.views.ptr.PtrFrameLayout$ScrollChecker.run(PtrFrameLayout.java:953)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5217)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
	at dalvik.system.NativeStart.main(Native Method)

出现机型HUAWEI C8813 android4.4.4，Coolpad 8675-A android4.1.1，请问是什么原因导致的？因为是第三方的错误统计，所以不知道具体的如何操作的。谢谢

**Comment by openproject** [comment]
最新的1.0.10已经解决了这个问题

**Comment by slowfall** [comment]
@openproject 多谢提醒。
