### ISSUE TITLE
运行您的代码，去掉一个参数报错.IllegalArgumentException: ViewHolderClass can not be initiated

### ISSUE THREAD

**Issue by playmans** [liaohuqiu/android-Ultra-Pull-To-Refresh#332]
![1](https://user-images.githubusercontent.com/26921420/38496200-31311af6-3c2f-11e8-8d43-5f12dadb23d4.png)

把mImageLoader参数去掉就会报错 不让贴图 我就直接复制错误了
java.lang.IllegalArgumentException: ViewHolderClass can not be initiated
                                                                                  at in.srain.cube.views.list.LazyViewHolderCreator.create(LazyViewHolderCreator.java:58)
                                                                                  at in.srain.cube.views.list.ListViewDataAdapterBase.setViewHolderClass(ListViewDataAdapterBase.java:44)
                                                                                  at in.srain.cube.views.ptr.demo.ui.viewpager.ViewPagerFragment.onCreateView(ViewPagerFragment.java:65)
                                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:870)
                                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1080)
                                                                                  at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:622)

**Comment by playmans** [comment]
求解
