### ISSUE TITLE
闪退啊

### ISSUE THREAD

**Issue by ximenhuangguaduo** [liaohuqiu/android-Ultra-Pull-To-Refresh#345]
2019-09-28 11:17:00.303 28744-28744/com.dongjinyu.teacher E/Minikin: Could not get cmap table size!
2019-09-28 11:17:00.305 28744-28763/com.dongjinyu.teacher E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
2019-09-28 11:17:00.323 28744-28770/com.dongjinyu.teacher E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@67a89cd
2019-09-28 11:17:00.424 28744-28744/com.dongjinyu.teacher E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dongjinyu.teacher, PID: 28744
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dongjinyu.teacher/com.dongjinyu.teacher.activity.MainActivity}: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class in.srain.cube.image.CubeImageView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3318)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3429)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
     Caused by: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class in.srain.cube.image.CubeImageView
     Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class in.srain.cube.image.CubeImageView
     Caused by: java.lang.ClassNotFoundException: Didn't find class "in.srain.cube.image.CubeImageView" on path: DexPathList[[zip file "/data/app/com.dongjinyu.teacher-PKA6TonUWxvpayZNkiogUA==/base.apk"],nativeLibraryDirectories=[/data/app/com.dongjinyu.teacher-PKA6TonUWxvpayZNkiogUA==/lib/arm64, /data/app/com.dongjinyu.teacher-PKA6TonUWxvpayZNkiogUA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:613)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.dongjinyu.teacher.activity.MainActivity.onCreate(MainActivity.java:27)
        at android.app.Activity.performCreate(Activity.java:7343)
        at android.app.Activity.performCreate(Activity.java:7333)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3429)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by MaBian123** [comment]
请问解决了么？怎么解决的？
