### ISSUE TITLE
android studio cannot render a preview 

### ISSUE THREAD

**Issue by kebbbnnn** [liaohuqiu/android-Ultra-Pull-To-Refresh#36]
AS cannot render a preview when I wrap a view with ultra-ptr it just show this exception:

java.lang.NullPointerException
	at in.srain.cube.views.ptr.PtrClassicDefaultHeader.hideRotateView(PtrClassicDefaultHeader.java:114)
	at in.srain.cube.views.ptr.PtrClassicDefaultHeader.resetView(PtrClassicDefaultHeader.java:109)
	at in.srain.cube.views.ptr.PtrClassicDefaultHeader.initViews(PtrClassicDefaultHeader.java:64)
	at in.srain.cube.views.ptr.PtrClassicDefaultHeader.<init>(PtrClassicDefaultHeader.java:37)
	at in.srain.cube.views.ptr.PtrClassicFrameLayout.initViews(PtrClassicFrameLayout.java:30)
	at in.srain.cube.views.ptr.PtrClassicFrameLayout.<init>(PtrClassicFrameLayout.java:21)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:379)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:99)
	at com.android.tools.idea.rendering.LayoutlibCallback.loadView(LayoutlibCallback.java:172)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:207)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:132)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:806)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:809)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:385)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:401)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:329)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:333)
	at com.android.tools.idea.rendering.RenderService$5.compute(RenderService.java:674)
	at com.android.tools.idea.rendering.RenderService$5.compute(RenderService.java:663)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
	at com.android.tools.idea.rendering.RenderService.createRenderSession(RenderService.java:663)
	at com.android.tools.idea.rendering.RenderService.render(RenderService.java:790)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:611)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1900(AndroidLayoutPreviewToolWindowManager.java:81)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:553)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:548)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:327)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by liaohuqiu** [comment]
In demo? Which view?

**Comment by kebbbnnn** [comment]
I created an activity with a listview then wrapped it with PtrClassicFrameLayout to give pull to refresh. At first when I didn't added the PtrClassicFrameLayout it shows the preview of the listview, but after adding PtrClassicFrameLayout AS didn't render the preview of the xml and trowed the exception I posted above. btw, nice lib so handy :) :+1:

**Comment by liaohuqiu** [comment]
Thank you. 
I've checked all the pages in demo. In AS1.0.1 they are all ok. What's the version of your AS? Could you push your code to github?

**Comment by kebbbnnn** [comment]
it's 0.8.14. I'll just update my AS for the mean time if it will fix the issue. thanks for immediate response! :)

**Comment by liaohuqiu** [comment]
It's post would be help. http://stackoverflow.com/questions/16592965/android-studio-layout-editor-cannot-render-custom-views
