### ISSUE TITLE
Missing application tag in androidmanifest causes robolectric failures

### ISSUE THREAD

**Issue by athkalia** [liaohuqiu/android-Ultra-Pull-To-Refresh#59]
Hello

Robolectric tests are failing because when I import your library the androidmanifest does not contain an application tag. If you don't need one then you still need to include an empty one:

    <application/> 

This is the exception.
```
WARNING: no system properties value for ro.build.date.utc
java.lang.IllegalArgumentException: Missing required <application/> element in .\gen-external-apklibs\in.srain.cube_ultra-ptr_1.0.7\AndroidManifest.xml
	at org.robolectric.AndroidManifest.parseAndroidManifest(AndroidManifest.java:155)
	at org.robolectric.AndroidManifest.getPackageName(AndroidManifest.java:474)
	at org.robolectric.AndroidManifest.getResourcePath(AndroidManifest.java:517)
	at org.robolectric.AndroidManifest.getIncludedResourcePaths(AndroidManifest.java:522)
	at org.robolectric.AndroidManifest.getIncludedResourcePaths(AndroidManifest.java:524)
	at org.robolectric.RobolectricTestRunner.createAppResourceLoader(RobolectricTestRunner.java:635)
	at org.robolectric.RobolectricTestRunner.getAppResourceLoader(RobolectricTestRunner.java:627)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:67)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:440)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:222)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

java.lang.RuntimeException: java.lang.IllegalArgumentException: Missing required <application/> element in .\gen-external-apklibs\in.srain.cube_ultra-ptr_1.0.7\AndroidManifest.xml
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:226)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.IllegalArgumentException: Missing required <application/> element in .\gen-external-apklibs\in.srain.cube_ultra-ptr_1.0.7\AndroidManifest.xml
	at org.robolectric.AndroidManifest.parseAndroidManifest(AndroidManifest.java:155)
	at org.robolectric.AndroidManifest.getPackageName(AndroidManifest.java:474)
	at org.robolectric.AndroidManifest.getResourcePath(AndroidManifest.java:517)
	at org.robolectric.AndroidManifest.getIncludedResourcePaths(AndroidManifest.java:522)
	at org.robolectric.AndroidManifest.getIncludedResourcePaths(AndroidManifest.java:524)
	at org.robolectric.RobolectricTestRunner.createAppResourceLoader(RobolectricTestRunner.java:635)
	at org.robolectric.RobolectricTestRunner.getAppResourceLoader(RobolectricTestRunner.java:627)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:67)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:440)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:222)
	... 19 more


Process finished with exit code -1

```

**Comment by liaohuqiu** [comment]
Do you mean:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="in.srain.cube.views.ptr"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-sdk
        android:minSdkVersion="8"
        android:targetSdkVersion="16" />

    <application />
</manifest>

```

**Comment by athkalia** [comment]
Yes.
This file here: https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh/blob/master/ptr-lib/AndroidManifest.xml

is missing the empty application tag.

    <application/>

**Comment by liaohuqiu** [comment]
Thank you for you feedback and `1.0.8.3-SNAHSHOT` is available now.
