### ISSUE TITLE
NullPointerException in sendCancelEvent method

### ISSUE THREAD

**Issue by JingHaifeng** [liaohuqiu/android-Ultra-Pull-To-Refresh#80]
`Exception:`

```
java.lang.NullPointerException
	at in.srain.cube.views.ptr.PtrFrameLayout.sendCancelEvent(PtrFrameLayout.java:854)
	at in.srain.cube.views.ptr.PtrFrameLayout.updatePos(PtrFrameLayout.java:370)
	at in.srain.cube.views.ptr.PtrFrameLayout.movePos(PtrFrameLayout.java:357)
	at in.srain.cube.views.ptr.PtrFrameLayout.access$400(PtrFrameLayout.java:17)
	at in.srain.cube.views.ptr.PtrFrameLayout$ScrollChecker.run(PtrFrameLayout.java:912)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5319)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
```

`In code(line 893 in last version):`

```
    private void sendCancelEvent() {
        if (DEBUG) {
            PtrCLog.d(LOG_TAG, "send cancel event");
        }
        MotionEvent last = mDownEvent;
        last = mLastMoveEvent;
        MotionEvent e = MotionEvent.obtain(last.getDownTime(), last.getEventTime() + ViewConfiguration.getLongPressTimeout(), MotionEvent.ACTION_CANCEL, last.getX(), last.getY(), last.getMetaState());
        dispatchTouchEventSupper(e);
    }
```

The mLastMoveEvent , it  might not  be initialized:
```
case MotionEvent.ACTION_MOVE:
                mLastMoveEvent = e;
                mPtrIndicator.onMove(e.getX(), e.getY());
                float offsetX = mPtrIndicator.getOffsetX();
                float offsetY = mPtrIndicator.getOffsetY();
```

**Comment by liaohuqiu** [comment]
Fixed now.
